spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/toll_station?useSSL=false&serverTimezone=UTC
      username: root
      password: root
server:
  port: 8081